
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculer", targetNamespace = "http://serviceCalculate/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculer {


    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Soustraction")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Soustraction", targetNamespace = "http://serviceCalculate/", className = "service.Soustraction")
    @ResponseWrapper(localName = "SoustractionResponse", targetNamespace = "http://serviceCalculate/", className = "service.SoustractionResponse")
    @Action(input = "http://serviceCalculate/Calculer/SoustractionRequest", output = "http://serviceCalculate/Calculer/SoustractionResponse")
    public int soustraction(
        @WebParam(name = "i", targetNamespace = "")
        int i,
        @WebParam(name = "j", targetNamespace = "")
        int j);

    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Addition")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Addition", targetNamespace = "http://serviceCalculate/", className = "service.Addition")
    @ResponseWrapper(localName = "AdditionResponse", targetNamespace = "http://serviceCalculate/", className = "service.AdditionResponse")
    @Action(input = "http://serviceCalculate/Calculer/AdditionRequest", output = "http://serviceCalculate/Calculer/AdditionResponse")
    public int addition(
        @WebParam(name = "i", targetNamespace = "")
        int i,
        @WebParam(name = "j", targetNamespace = "")
        int j);

    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://serviceCalculate/", className = "service.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://serviceCalculate/", className = "service.DivisionResponse")
    @Action(input = "http://serviceCalculate/Calculer/divisionRequest", output = "http://serviceCalculate/Calculer/divisionResponse")
    public int division(
        @WebParam(name = "i", targetNamespace = "")
        int i,
        @WebParam(name = "j", targetNamespace = "")
        int j);

    /**
     * 
     * @param i
     * @param j
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Multiplication")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Multiplication", targetNamespace = "http://serviceCalculate/", className = "service.Multiplication")
    @ResponseWrapper(localName = "MultiplicationResponse", targetNamespace = "http://serviceCalculate/", className = "service.MultiplicationResponse")
    @Action(input = "http://serviceCalculate/Calculer/MultiplicationRequest", output = "http://serviceCalculate/Calculer/MultiplicationResponse")
    public int multiplication(
        @WebParam(name = "i", targetNamespace = "")
        int i,
        @WebParam(name = "j", targetNamespace = "")
        int j);

}
