
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceCalculateService", targetNamespace = "http://serviceCalculate/", wsdlLocation = "http://localhost:8584/?wsdl")
public class ServiceCalculateService
    extends Service
{

    private final static URL SERVICECALCULATESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECALCULATESERVICE_EXCEPTION;
    private final static QName SERVICECALCULATESERVICE_QNAME = new QName("http://serviceCalculate/", "ServiceCalculateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8584/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECALCULATESERVICE_WSDL_LOCATION = url;
        SERVICECALCULATESERVICE_EXCEPTION = e;
    }

    public ServiceCalculateService() {
        super(__getWsdlLocation(), SERVICECALCULATESERVICE_QNAME);
    }

    public ServiceCalculateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECALCULATESERVICE_QNAME, features);
    }

    public ServiceCalculateService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECALCULATESERVICE_QNAME);
    }

    public ServiceCalculateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECALCULATESERVICE_QNAME, features);
    }

    public ServiceCalculateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceCalculateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculer
     */
    @WebEndpoint(name = "CalculerPort")
    public Calculer getCalculerPort() {
        return super.getPort(new QName("http://serviceCalculate/", "CalculerPort"), Calculer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculer
     */
    @WebEndpoint(name = "CalculerPort")
    public Calculer getCalculerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceCalculate/", "CalculerPort"), Calculer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECALCULATESERVICE_EXCEPTION!= null) {
            throw SERVICECALCULATESERVICE_EXCEPTION;
        }
        return SERVICECALCULATESERVICE_WSDL_LOCATION;
    }

}
